#theme: jekyll-theme-hacker
remote_theme: ankitsultana/researcher@gem
title: dash-program
url: "https://samuele-mattiuzzo.github.io"
baseurl: "/dash-program"
author: "Samuele Mattiuzzo"

markdown: kramdown
tracking_id: #

footer: yes
footer_url: "https://github.com/samuele-mattiuzzo"
footer_text: "Samuele Mattiuzzo"

sass:
    style: compressed
    sass_dir: _sass
